import { pgTable, text, timestamp } from 'drizzle-orm/pg-core'

// App tables live here. Auth tables are in auth-schema.ts (generated by Better Auth CLI).
// When adding new tables, run: npm run db:generate && npm run db:migrate

export const posts = pgTable('posts', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  title: text('title').notNull(),
  content: text('content'),
  authorId: text('author_id').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
})
